### ISSUE TITLE
adding DASmap DASrealign REPqv REPtrim

### ISSUE THREAD

**Issue by mictadlo** [rrwick/DASCRUBBER-wrapper#1]
Hi,
Do you have any plans to add `DASmap`, `DASrealign`, `REPqv` and `REPtrim` from the DASCRUBBER project to this wrapper? 

If not then do you know how to run them because I got lost [here](https://github.com/thegenemyers/DASCRUBBER/issues/11)?

Thank you in advance.

Michal

**Comment by rrwick** [comment]
Hi Michal,

I don't think `REPqv` and `REPtrim` are necessary - my interpretation is that they just produce the output of `DASqv` and `DAStrim` in case you want the output again without running those tools again.

`DASmap` seems to associate which parts of your new scrubbed reads correspond to which parts of your original reads. Might be handy for some workflows, but not needed if all you're doing is producing a scrubbed read set.

Finally, I don't plan to `DASrealign` because that seems to remake the all-vs-all read alignments using the new scrubbed reads. But this wrapper script is just about making a scrubbed read set, not continuing on to assemble it, so I don't need to realign the reads - once they're scrubbed I'm done!

I hope that makes sense. Let me know if you have any more questions or if you think I've misinterpreted what the tools are for.

Ryan

**Comment by mictadlo** [comment]
Thank you.
