### ISSUE TITLE
Comment. Not working on larger datasets

### ISSUE THREAD

**Issue by BenjaminSchwessinger** [rrwick/DASCRUBBER-wrapper#5]
Hi Ryan,
thanks much for putting this together. I just wanted to let you know that the current version is not working for larger datasets (e.g. 10Gb of data). 

The issue is with the function def align_reads line 302. Your daligner call does not make use of the split databases but uses the complete reads database. 'Subdatabases' generated with DBsplit can be addressed with reads.1 etc (see [here](https://github.com/thegenemyers/DAZZ_DB) for detail under 9.) . So for bigger datasets the daligner jobs would have to make use of all the split databases doing all vs. all alignments similar to the first step in FALCON. This would profit from distributed computing on a cluster. I am currently not able to fix this myself but thought other may know a fix.

Just sharing this and not expecting a fix as for your smaller bacterial datasets this isn't really an issue.

**Comment by rrwick** [comment]
Yes, you're absolutely right - this wrapper doesn't use any of DALIGNER's fancy HPC capabilities. I think that if you're dealing with a huge dataset, you should probably be running the Dazzler commands directly, instead of using this wrapper. The only thing you might still need this wrapper for is its very first step: converting read names (which may be Nanopore reads) to a PacBio-like format appropriate for Dazzler.

I've added [a new section to the README](https://github.com/rrwick/DASCRUBBER-wrapper#large-datasets) outlining my recommendations for such a scenario. Thanks for letting me know!

Ryan
